name: Refresh NSE ISIN dataset

on:
  push: 
  schedule:
    # Every Monday at 02:00â€¯UTC
    - cron: '0 2 * * 1'
    # workflow_dispatch: {}
jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests sqlite3
      - name: Run main script
        run: |
          cd scripts/
          python main.py
      - name: Export as SQL
        run: |
          cd scripts/
          python isin_to_sql.py
      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nse-isin-data
          path: data/
